### ISSUE TITLE
Add the admin UI update banner in admin panel

### ISSUE THREAD

**Issue by robinkwilson** [mozilla/hubs-cloud#153]
![image](https://user-images.githubusercontent.com/29560735/103929381-188a4080-50d2-11eb-8678-349c0079059d.png)

**Comment by blairmacintyre** [comment]
Is there any info anywhere on the new UI?  We've been doing mods to Hubs client, and it would be great to know what's coming.  Since we won't be "releasing" the project sites before March 25th, we could also (if possible) work with code in a dev branch at some point, when it's there, to try and be ready for the new update.
