### ISSUE TITLE
control which subset of Scenes can be used to create new rooms

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#23]
For VR 2020, I would like to have the top page have HTML explaining that they should go to the ieeevr.org/2020/online page to join the online experience and explaining other things about discord, etc. as discussed in #19 

But, I would also like the opportunity to allow folks to create their own private chat rooms.  We could just direct them to "normal hubs" to do that, but I wouldn't mind these private rooms having some custom features or (at least) use our instance (since I think we'd want to do that eventually, and I'd like to capture the usage costs).

So, it would be nice if we can let folks create a room from a subset of the known scenes.  I don't think we want people creating rooms with our "main shared room" scenes, for example.  I would like them to go and use those rooms.

**Comment by gfodor** [comment]
I agree this use-case isn't perfectly met yet, here's what you can do now:

- If you tag a scene `default`, it will be selected randomly from all `default` scenes when creating a room
- If you disable Spoke, users will only be able to select scenes you approve (and likely will only discover scenes you feature)
- We'll be shipping 'public rooms' soon, which can be listed on the homepage. These obviously can use scenes that are not featured or listed since they're going to be set up by you, the administrator.

So I think the best you could do now is only approve/feature the scenes you want users to use, set all of those to `default` (so they will get a random one during room creation), and then instruct users to use the "Change Scene" functionality to choose the one that suits them if the randomly chosen one doesn't. Additionally, once we ship public rooms, that will give you the ability to have de-facto "main shared rooms" that use distinct scenes.

It sounds like what you're interested in beyond this is the ability for the user to select a scene *before* creating a room, from the set of defaults. This was how it worked in an earlier design of hubs, but we moved away from having that additional choice on the homepage (and also only have one default scene) since we felt it was better to have users learn how to change scenes of a room in a unified way. Re-introducing scene selection before room creation may make sense however for some of the Hubs Cloud use cases, though, so we can revisit.

**Comment by blairmacintyre** [comment]
The `default` scene selection is a good start. 

Perhaps adding something like a `private` tag so that room doesn't show up in the list of possible Scenes (featured or otherwise) in select scene UI?

Regarding public rooms:  is the intent here that these will probably only get used when there are moderators present, or some sort of authentication (e.g., discord or otherwise)?

**Comment by gfodor** [comment]
If you never `Approve` a scene, then it will not be discoverable through search. However scenes that you import in the admin console for convenience are auto-approved. To revoke their visibility, just go to the scene in the admin console, click edit, then set the state to unlisted.

For public rooms -- in general, there's a lot of people who want the ability to have open ended public rooms that don't require out-of-band link sharing, so this makes that possible (for better or worse, in the case where they are un-moderated spaces.) It's up to the end user to decide how much to lock down permissions and ensure there are moderators in-room, but right now there's no special story there for these public listings. (Other than that we'd discourage people from using them in scenarios where abuse is a factor.) There's no new authentication/authorization for these, so ultimately if a person shows up who is persistent and wants to cause trouble the only remedy right now would be to close the room and revert to private sharing.

**Comment by gfodor** [comment]
Can you confirm @blairmacintyre if there is still a gap here?

**Comment by blairmacintyre** [comment]
If the public rooms feature ships, that's probably good.  I could imagine, combined with the authentication we've been discussing, that we could just put all our current active conference rooms on the front page, and perhaps include a "create a new room" and only have the scenes we care about active.  So, I think this can be closed.

**Comment by gfodor** [comment]
cool sounds good
