### ISSUE TITLE
Can I use ALL external domains with hubs cloud?

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/hubs-cloud#24]
All of the recipes assume that at least some domain is going to be set up inside Route53 (e.g., the .link domain).   Plus, for the instructions to use Cloudflare, it picks a domain name for me.

If I want to use all subdomains off of my organization, I need to be able to specify all of them.  For example, at Georgia Tech, I would like to use
- hubs.ael.gatech.edu for my lab's hubs domain
- link.ael.gatech.edu for the link (yes, it's not short, but that's fine)
- hubs-internal.ael.gatech.edu for the internal domain
- at least specify a prefix for the cloudflare one (.ael.gatech.edu)

If this is possible, a receipe showing it would be great.  If not yet possible, it would be great to make it possible.

**Comment by gfodor** [comment]
No, unfortunately right now you have to have at least an internal domain, we use the internal domain for a few things:

- Internal endpoints like cloudfront and application load balancers. We could theoretically use IPs or the auto-generated amazon domain names, but its much nicer to have invariant domain names regardless of the underlying resource. (Eg keeps links working, avoids caching issues, etc)

- Servers themselves get a unique internet DNS. This helps with diagnostics, logging, etc. We rely upon these DNS entries for service discovery, DNS round robin, etc.

**Comment by gfodor** [comment]
A workflow for customizing the cloudflare domain is theoretically possible, the current "we give you the domain name" approach was there for two reasons:

- Making it so you don't have to think of a domain name, since you will need a domain for this and it's unlikely an existing top level domain you have would be the right choice

- We burned this into the CSP, but this is no longer the case: as of recently, the CSP is computed dynamically

Given we fixed the CSP issue that was the main blocker towards a custom domain for the Cloudflare worker.

**Comment by gfodor** [comment]
Oh, and for AWS we require the shortlink domain to be on Route 53 but that seems possible to change -- the thinking was since we at least require Route 53 for the internal domain, most users would only get benefits from the additional complexity of the top domain name, since they'd likely be registering a short link domain for the project. (If we made the short link domain non-Route 53 bound, we'd have to do similar configuration cruft as we do with the normal domain with regards to SSL certificates, etc, which seemed not worth doing if we could assume Route 53 wouldn't be a non-starter for shortlink domains, given that internal domains are strictly necessary.)

**Comment by blairmacintyre** [comment]
Ok, thanks.  The high order bit is that there are good reasons for having Route 53 for some domains, so I can't really avoid it (i.e., I can't expect to use .gatech.edu domains for everything).
