### ISSUE TITLE
 AWS cloudformation gets ROLLBACKED

### ISSUE THREAD

**Issue by shifatul-i** [mozilla/hubs-cloud#92]
I was trying to create hubs-cloud instance on AWS cloudformation but I get the following Error Message, What am I doing wrong?

![image](https://user-images.githubusercontent.com/3328263/89207872-4e9a2600-d570-11ea-85e0-347ddd2fe72d.png)

I was following this tutorial: https://www.youtube.com/watch?v=MyGJ0s4XjTA

**Comment by robin-k-wilson** [comment]
This would be a great [Hubs Official Github Discussions](https://github.com/mozilla/hubs/discussions) thread!

You're running into a SSL Cert problem ([InternalZoneSSLCert Solutions documentation here](https://hubs.mozilla.com/docs/hubs-cloud-aws-troubleshooting.html#externalzonesslcertlocalifeast-error-or-internalzonesslcert-error-or-timeout)) or one of the domains is configured incorrectly. Here's another set of tutorials, that include the purchasing of domains: [Part 1](https://www.youtube.com/watch?v=2K7P8jFyHNc) and [Part 2](https://www.youtube.com/watch?v=W0erzlDpo0U)

I'm going to close this issue since [Discussions](https://github.com/mozilla/hubs/discussions) is the place to have this conversation and the rollback seems to be working correctly (if there's a problem with one of the stack resources, it rolls back as the correct behavior).

Thank you!
